### ISSUE TITLE
Add setEncoderIndexSource API

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#121]
https://github.com/robotpy/allwpilib/commit/1b5cabc0d100421a238cac9a13ad1178b2b04c9d

... I think we need to rebuild the HAL binary before we make this change, correct?

**Comment by PeterJohnson** [comment]
Yes, but my buildbot regularly builds binaries (see http://www.tortall.net/~robotpy/hal/) so it's just a matter of updating hal_version in hal-roborio/setup.py at the same time the function is added to hal-base.

**Comment by computer-whisperer** [comment]
I can work on this.

**Comment by computer-whisperer** [comment]
This was finished in #130
