### ISSUE TITLE
os.getgroups() produces segmentation fault

### ISSUE THREAD

**Issue by dangyogi** [robotpy/robotpy-wpilib#125]
Trying to execute the os.getgroups function in python produces a segmentation fault.

```
$ python3
>>> import os
>>> os.getgroups()
```

This works OK on my ubuntu desktop running python 3.4.1.

**Comment by dangyogi** [comment]
This is not something that I need to do, so is a low priority...

**Comment by virtuald** [comment]
This should be filed against https://github.com/robotpy/roborio-packages instead.
