### ISSUE TITLE
Need to port the SerialPort object

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#128]
https://github.com/robotpy/allwpilib/blob/master/wpilibj/wpilibJavaDevices/src/main/java/edu/wpi/first/wpilibj/SerialPort.java

**Comment by PeterJohnson** [comment]
I guess for compatibility, but is there a reason not to use the native Python libraries for serial ports?

**Comment by virtuald** [comment]
That's true enough. If we decide not to do it, we probably should note it somewhere in a list of things that we're explicitly not porting.

**Comment by auxiliary-character** [comment]
Either a wrapper around native Python library or a port would be appreciated.

**Comment by virtuald** [comment]
@auxiliary-character , have you tried [pyserial](http://pyserial.sourceforge.net/)? You can use the robotpy installer to install pip packages on the robot (see [this page](http://robotpy.readthedocs.org/en/latest/installer.html#download) for instructions on how to use the installer).

**Comment by auxiliary-character** [comment]
@virtuald That may work. I'm looking at maybe porting the Java version of the [navx-mxp](https://code.google.com/p/navx-mxp/) code, which depends upon the wpilibj SerialPort. Looking through the hardware documentation, I may want to do I2C or SPI from scratch instead, but it would be convenient to just have a SerialPort class that behaves the same as it does in Java.

**Comment by virtuald** [comment]
You're more than welcome to do the port and submit a pull request ;)

**Comment by virtuald** [comment]
The mxp thing would be a good addition to https://github.com/robotpy/robotpy-wpilib-utilities, actually.

**Comment by auxiliary-character** [comment]
Awesome. The scope's a little beyond what I'm used to, and I [might not get much time to test it](http://www.reddit.com/r/FRC/comments/2scrp3/totes_and_hoes_aka_a_meme_that_was_made_during_a/cnpewyk), but I'll definitely send it your way if/when it happens.

**Comment by virtuald** [comment]
Lol, good story at the link.

**Comment by virtuald** [comment]
Also, if you can do the translation, we can review it pretty easily. As long as it matches the java code reasonably closely, it should be ok.

**Comment by auxiliary-character** [comment]
Awesome.

**Comment by virtuald** [comment]
@auxiliary-character did you end up getting that to work?

**Comment by auxiliary-character** [comment]
We got a [terrible hackish version](https://github.com/DenfeldRobotics4009/2015_Lopez_Jr/blob/master/imu_simple.py) using regexes that doesn't verify checksums, and doesn't include acclerometer or quaternion data. I think we'll work on a proper version post-season.

**Comment by virtuald** [comment]
@auxiliary-character did you guys ever make a proper port of the MXP stuff? Our team just got one. :)

**Comment by computer-whisperer** [comment]
I started working on a proper port somewhere, though I dont remember how far I got.

**Comment by auxiliary-character** [comment]
Yeah, we never did. I have been procrastinating a lot. Should be pretty easy, though; the [I2C/SPI registers](http://www.pdocs.kauailabs.com/navx-mxp/advanced/register-protocol/) are documented pretty well. I imagine it would be pretty similar to your [adxl345 driver](https://github.com/robotpy/robotpy-wpilib/blob/master/wpilib/wpilib/adxl345_i2c.py) in implementation.

**Comment by virtuald** [comment]
BTW, I've pushed my initial complete NavX MXP implementation to https://github.com/robotpy/robotpy-wpilib-utilities/tree/mxp .. it's a lot easier this year, as they moved a bunch into the firmware.

**Comment by virtuald** [comment]
Decided I don't care about this, so closing.
