### ISSUE TITLE
Probably should use a linter on this project

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#13]
I've never used it before, but I've heard good things. Pydev uses it underneath the hood, and it helps me catch errors.

**Comment by auscompgeek** [comment]
pylint always seemed to be a bit noisy for me. Not that I'm against the use of pylint (it's been a while since I've tried running pylint over my own code), but we should also consider other linters we could use, such as flake8.

**Comment by virtuald** [comment]
Sure, that seems fine to me.
