### ISSUE TITLE
COMPAT: AnalogTrigger + MXP remap fix

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#137]
https://github.com/robotpy/allwpilib/commit/215002e487050bcbb5dfede04e0e8fd4a7c0411a

**Comment by virtuald** [comment]
This appears to be a HAL-only change, so if we bumped the HAL version this would work. I don't have a roboRIO available at the moment to test a new HAL on, so I'm loathe to do this after build season has ended.

**Comment by computer-whisperer** [comment]
I have access to a couple of unbagged RoboRIOs. If you were to send me the compiled HAL I could probably run some tests with it.

**Comment by virtuald** [comment]
The hal's are available at http://www.tortall.net/~robotpy/hal/ . If you change hal_version at the top of https://github.com/robotpy/robotpy-wpilib/blob/master/hal-roborio/setup.py, then it will download the latest hal when building the setup package. You can use `devtools/build_and_deploy.sh` to deploy the version you have in tree.

**Comment by computer-whisperer** [comment]
Is there anything in particular that you would like for me to test for? I just confirmed that it starts and runs my team's code just fine, though I haven't run any real hardware with it yet.

**Comment by computer-whisperer** [comment]
This can probably be closed, since I assume the HAL will get a major version bump before we are done with RobotPy 2016
