### ISSUE TITLE
HAL STATUSFUNC should distinguish between warnings and errors

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#143]
This bug happens particularly when accessing the PDP. See http://www.chiefdelphi.com/forums/showthread.php?t=135145 for details.

**Comment by virtuald** [comment]
This bug may have happened because of https://github.com/robotpy/allwpilib/commit/7bdd91a058457db7b6d294137a8de26d47163e6d ... I can't see what artf4014 is though.

**Comment by virtuald** [comment]
@PeterJohnson can you look at the beta tracker and see what artf4014 is?

**Comment by PeterJohnson** [comment]
When there are multiple PCMs, reading the solenoid values from any PCM returns the value from PCM0. This is demonstrated in the attached sample programs which set PCM0 solenoid to Reverse and PCM1 solenoid to Forward. Reading both using GetAll returns 2 (reverse) for both PCM 0 and PCM1. It should return 2 for PCM0 and 1 for PCM1.  	

The PCM ID is not used when getting status in hal/ctre/PCM.cpp, so all status is from PCM 0

**Comment by virtuald** [comment]
Thanks!
