### ISSUE TITLE
Add convenience function for testing encoders

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#152]
Would be useful to add a `get_encoder(pinA, pinB)` that would scan the list of encoders and find a matching encoder, and return that dictionary. Perhaps even assert if it doesn't exist?

From http://www.chiefdelphi.com/forums/showthread.php?t=137638

**Comment by schreiaj** [comment]
Along these lines, it might be useful to have a simple convenience function for mapping PWM output -> encoder ticks given an max_rpm, reduction, and counts_per_revolution (cpr). Should help cut down on the number of magic numbers in code.

**Comment by auscompgeek** [comment]
OBE
