### ISSUE TITLE
Add PEP 0484 type hinting?

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#157]
This could be useful to combine with @computer-whisperer's API checkers. Or, pyfrc could automatically run it as part of tests before deploying code -- that would be really cool. 

See http://mypy-lang.org/ and https://www.python.org/dev/peps/pep-0484/

**Comment by CrazyPython** [comment]
@virtuald 

This needs to be implemented NOW. It really helps my IDE a lot. Seriously.

**Comment by virtuald** [comment]
I will accept pull requests. 👍

**Comment by auscompgeek** [comment]
I feel like possibly taking this up. I'm just thinking, should we use `*.pyi` stub files, or should we just annotate the source?

**Comment by Twinters007** [comment]
If you annotate the source it'll show up if you aren't using an IDE and you can view them easily just by going into the file.

**Comment by virtuald** [comment]
My opinion is that it should be done in the source, otherwise it'll never get updated.

You can most likely use the API checker stuff to do a lot of the work for you.

**Comment by auscompgeek** [comment]
We should also make devtools/convert_javadoc.html convert the type information to type hints too.

**Comment by virtuald** [comment]
That's a good idea.

**Comment by auscompgeek** [comment]
Just something I've noticed: full-blown type hints don't seem to look very nice when rendered in the docs. They might look nicer with forward-references, but I haven't had a chance to try that.

**Comment by nhubbard** [comment]
@virtuald I am working on this in my fork. The effort is few and far in between, but it will eventually be pull-requested into the master branch.

**Comment by virtuald** [comment]
@nhubbard awesome. Probably better to send the PRs in batches instead of the whole thing all at once.

**Comment by virtuald** [comment]
I think this is mostly done?
