### ISSUE TITLE
2016 HAL Fixes

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#158]
Lots to do here.. 

* Multiwait stuff
* CTRE additions for CANTalon
* PCM

The hal scanner indicates 66 errors. Let's see how many of them I can kill tonight.

**Comment by computer-whisperer** [comment]
A lot of the CANTalon errors are false negatives, something to do with how the CTRE code is split from the rest of the HAL namespace iirc. I never got around to fixing the scanner.

FYI I am currently finishing up a vacation, should be able to get back working on robotpy later this week.

**Comment by virtuald** [comment]
I think I got em all, as of 678e326
