### ISSUE TITLE
Add 2017 example projects

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#165]
Example projects are in the [eclipse plugins repo](https://usfirst.collab.net/gerrit/gitweb?p=eclipse_plugins.git;a=tree;f=edu.wpi.first.wpilib.plugins.java/resources/templates;hb=HEAD;tflink=projects.wpilib/scm.Eclipse_Plugins).

Looks like there's a few samples that we're missing... Gyro, GyroMecanum, Potentiometer, PotentiometerPID, Ultrasonic, UltrasonicPID.

There are also 3 vision projects, which I think are less important: 2015Vision, AxisCameraSample, IntermediateVision.

**Comment by Twinters007** [comment]
Eclipse Plugins Repo link seems to be broken

**Comment by virtuald** [comment]
It's possible that you need to be logged in to their site to see it. I mirrored it to github [here](https://github.com/virtuald/wpilib_eclipse_plugins/tree/master/edu.wpi.first.wpilib.plugins.java/resources/templates).

**Comment by virtuald** [comment]
Updated this for 2017.

**Comment by Twinters007** [comment]
what's changed for 2017

**Comment by virtuald** [comment]
The example projects are in their own git repo, closing this.
