### ISSUE TITLE
CANTalon needs to be updated

### ISSUE THREAD

**Issue by Arhowk** [robotpy/robotpy-wpilib#175]
~1000 lines...

E/ I've widdled it down and it seems to be much easier than I thought.. I'll post an update soon and confirm it works (we are using multiple PID controls on our bot so we should be a good test)

**Comment by virtuald** [comment]
Yes, the release notice for 2016.0 mentions that the CANTalon support has not been updated yet. I would be very happy if you did it. :)

**Comment by virtuald** [comment]
Also, for translating docstrings, see https://github.com/robotpy/robotpy-wpilib/blob/master/devtools/convert_javadoc.html -- it will do most of the work for you.

**Comment by Arhowk** [comment]
Yeah I have about ~15 hours or so at robotics this weekend so I'll get it done in the downtimes.

I just copy pasted the java code in and replaced "public void" with "def" to start.. is the docstring thing needed? (what wouldve been nice is an update diff scanner so I can actually see which functions are new and which existed last year)

**Comment by virtuald** [comment]
There is an update diff scanner thing also, but it requires validation the first time around. Checkout devtools/validate.py

You can do it by hand if you want, but the docstring thing is easier to use as it automatically converts the function definition to 'def foo' also. And I won't accept a PR without the docstrings if they exist in the Java -- our documentation should be at least as good as theirs.

**Comment by virtuald** [comment]
Also, you can see what stuff is already implemented and not by using the spec scanners. Requires plyj to be installed. I haven't integrated it in very well yet, but something like this from the tests directory...

```
$ cat scanj.sh 
#!/bin/bash

cd `dirname $0`
python spec_scanners/wpilib_scanner.py ~/src/frc/allwpilib/wpilibj "$@"
```

**Comment by virtuald** [comment]
Did you make progress on this?

**Comment by Arhowk** [comment]
Not more than I had previously. I setup a talon SRX to test and everything
that we had previously seems to still work fine. Because of this, it
dropped in my priority list for the time being.

**Comment by virtuald** [comment]
Since this has to get done at some point, I started on it too. I think the only piece left is the giant bit of logic at the end.

https://github.com/robotpy/robotpy-wpilib/tree/can2016

**Comment by Arhowk** [comment]
So sorry.. I'm the only programmer (and head electrical) for my team so I tend to get wrapped up in projects and forget about everything.
