### ISSUE TITLE
PIDController.setSetpoint clears the error

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#188]
If you call it repeatedly with the same value, then onTarget will pretty much never be true.

**Comment by virtuald** [comment]
Related to https://github.com/wpilibsuite/allwpilib/pull/17

**Comment by virtuald** [comment]
Bug filed at https://github.com/wpilibsuite/allwpilib/issues/29

**Comment by virtuald** [comment]
There was supposed to be a fix for this, but it never made it upstream?

**Comment by auscompgeek** [comment]
Upstream has now fixed this by using LinearDigitalFilter internally.

**Comment by auscompgeek** [comment]
Looks like this was fixed in c532d7846dd8250307b17d451ffbe5d101cfd0c9.
