### ISSUE TITLE
onTarget() doesn't actually have any function?

### ISSUE THREAD

**Issue by bb20basketball** [robotpy/robotpy-wpilib#196]
I asked the Delphi community why the sample PID program wasn't working, even with me trying to use the onTarget() to stop the loop and a user pointed out that there isn't actually any function to onTarget other than to raise a ValueError. Thread: https://www.chiefdelphi.com/forums/showthread.php?threadid=149281

**Comment by virtuald** [comment]
If you call `setXXXTolerance` first, it will replace the onTarget function. See https://github.com/robotpy/robotpy-wpilib/blob/master/wpilib/wpilib/pidcontroller.py#L445
