### ISSUE TITLE
Use flat namespace for hal_data instead of nested dictionaries

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#205]
I'm sure there was a reason I didn't do this before... but basically, right now we access the data like so:

```
hal_data['pdp']['has_source']
hal_data['solenoid'][0]['value']
... etc
```

I want to change it to this instead:

```
hal_data['pdp.has_source']
hal_data['solenoid.0.value']
```

This will make a few things easier to do, in particular it'll be significantly easier to create diffs of the hal_data if you maintained separate sets of dictionaries for I/O, as it would just be `dict.update()` to copy the updates over. This would be useful if trying to ship the data over a websocket, as you would only need to send changes.

There also would be fewer dictionary lookups in the simulator execution, which is probably a good thing. We could cache a lot of the keys in the fake port objects and such so that we're not constantly computing 

For backwards compatibility, we could define a dictionary shim that would map the existing dictionaries to the new keys (and this might be useful for teams writing custom physics... ).

If you have opinions, state them here. I'm not 100% sold on it yet.

**Comment by virtuald** [comment]
@Twinters007 @computer-whisperer may have opinions on this?

**Comment by Twinters007** [comment]
I like it. Seems like a good change. What's keeping you from being 100% sure?

**Comment by virtuald** [comment]
This will have to wait until 2018.

**Comment by virtuald** [comment]
Time to revisit this... I had thought of a reason to not do it, but I've forgotten it.

**Comment by Twinters007** [comment]
Could it be accessing dicts based on variables will be easier?

**Comment by twinters007** [comment]
```
def __getattr__(self, attr):
        return self.get(attr)

def __setattr__(self, key, value):
    self.__setitem__(key, value)
```
Would this simple solution work for hal?

**Comment by auscompgeek** [comment]
I think this will have to wait until next year. It's a bit late to be thinking of architectural changes now.

**Comment by virtuald** [comment]
Hm. Is now the time for change?

**Comment by virtuald** [comment]
Hm, I think the reason to not do it is because NotifyDict adds overhead and it would have to be added at the top level... but honestly, I don't know that anything actually uses it?

**Comment by ArchdukeTim** [comment]
https://docs.python.org/3/library/types.html#types.SimpleNamespace

could this work?

**Comment by virtuald** [comment]
Sad, will have to push this off to 2020 methinks.

**Comment by virtuald** [comment]
OBE. Maybe.
