### ISSUE TITLE
Extract CANTalon to robotpy-ctre package

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#212]
Related issues:

* #206
* #208

Package management in python is trivial, so I think it makes sense for these types of things to be separate packages, despite that the RobotPy project will be maintaining them. New repo will be at https://github.com/robotpy/robotpy-ctre

**Comment by virtuald** [comment]
Removed CANTalon in ed58c9e67e334057d6416e6de6859f7f6b549ffe

**Comment by vanjac** [comment]
Maybe it would be good to have a placeholder CANTalon class that prints a deprecation warning when methods are called, to prevent initial confusion when teams update to the new changes?

**Comment by virtuald** [comment]
I could add the following:

```
class CANTalon:
    def __init__(self):
        raise ValueError("CANTalon has moved to ctre.CANTalon, you must install robotpy-ctre")
```

**Comment by vanjac** [comment]
That would work. __init__ could allow *args and **kwargs so it would ignore any arguments.

**Comment by virtuald** [comment]
CANTalon support will be delayed, hopefully get it done soon.

**Comment by vanjac** [comment]
No way to use CANTalons at all yet?

**Comment by virtuald** [comment]
Yeah, lots of other things had to be done, and there's only so much time to do it. It is my number one priority for this weekend (after reading the rules for the game).

**Comment by vanjac** [comment]
Will tests for robot code with talons still pass?

**Comment by virtuald** [comment]
The PWM interface for Talon and TalonSRX are still there. Only the CAN version of the motor controller is affected by this.

**Comment by virtuald** [comment]
I've got something working, and I think I might have a full solution available tomorrow night.

**Comment by virtuald** [comment]
Released last night.
