### ISSUE TITLE
hal.HALReport missing

### ISSUE THREAD

**Issue by vScourge** [robotpy/robotpy-wpilib#244]
When running the simulator, the constructor for robotpy_ext.control.xbox_controller.XboxController failed, saying the class hal.HALReport was missing.  This was with robotpy 2017.0.0, running on Windows 10.

File "c:\Python34\Lib\site-packages\robotpy_ext\control\xbox_controller.py", line 23, in __init__
  hal.HALReport(hal.HALUsageReporting.kResourceType_Joystick, port)
builtins.AttributeError: 'module' object has no attribute 'HALReport'

**Comment by virtuald** [comment]
Yep, definitely a bug. BTW, there's an XBoxController in wpilib now, I'd recommend using that instead.

**Comment by virtuald** [comment]
Fixed in robotpy-wpilib-utilties 2017.0.1
