### ISSUE TITLE
PyNetworkTables downloading as whl instead of tar.gz

### ISSUE THREAD

**Issue by onenerdyguy** [robotpy/robotpy-wpilib#248]
On a fresh roborio, get the following error when attempting to install:
Collecting pynetworktables>=2017.0.1 (from wpilib)
  Could not find a version that satisfies the requirement pynetworktables>=2017.0.1 (from wpilib) (from versions: )
No matching distribution found for pynetworktables>=2017.0.1 (from wpilib)
Command '['C:\\Users\\bob\\Desktop\\robotpy-2017.0.1\\win32\\plink.exe', '-pw', '', 'admin@172.22.11.2', 'bash opkg_cache/install_opkg.sh && /usr/local/bin/pip3 install --no-index --find-links=pip_cache --pre --upgrade wpilib robotpy-hal-base robotpy-hal-roborio robotpy-wpilib-utilities']' returned non-zero exit status 1.

Further investigation shows in the pip_cache folder that we have  a .whl file for pynetworktables instead of tar.gz and it fails out.

**Comment by virtuald** [comment]
A new release has been made. The release builder needs to be fixed for pip 9.x, but works fine for 8.x
