### ISSUE TITLE
Installer script not downloading mjpg-streamer

### ISSUE THREAD

**Issue by czhao39** [robotpy/robotpy-wpilib#255]
Here is the output I get when I run `py -3 installer.py download-opkg mjpg-streamer`:

> Downloading http://www.tortall.net/~robotpy/feeds/2017/Packages
100%
Downloading http://download.ni.com/ni-linux-rt/feeds/2016/arm/ipk/cortexa9-vfpv3/Packages
100%
Traceback (most recent call last):
  File "installer.py", line 1009, in <module>
    retval = main()
  File "installer.py", line 990, in main
    retval = options.cmdobj(options)
  File "installer.py", line 792, in download_opkg
    package_list = opkg.resolve_pkg_deps(options.packages)
  File "installer.py", line 180, in resolve_pkg_deps
    deps =  self._get_pkg_deps(pkg)
  File "installer.py", line 152, in _get_pkg_deps
    info = self.get_pkginfo(name)
  File "installer.py", line 146, in get_pkginfo
    raise OpkgError("Package '%s' is not in the package list (have you downloaded it yet?)" % name)
__main__.OpkgError: Package 'mjpg-streamer' is not in the package list (have you downloaded it yet?)

**Comment by virtuald** [comment]
Yeah, I haven't compiled mjpg-streamer for 2017 yet. I'm not planning on doing so, in favor of using cscore, unless someone gives me a compelling reason. 

See the [README](https://github.com/robotpy/roborio-packages) at roborio-packages.
