### ISSUE TITLE
Digital Output Attribute Error

### ISSUE THREAD

**Issue by codetheweb** [robotpy/robotpy-wpilib#261]
I'm trying to use a digital output.  When setting the value with `output.set(True)`, I'm getting this error on upload:
```
self = <wpilib.digitaloutput.DigitalOutput object at 0x10e9cea20>, value = True

    def set(self, value):
        """Set the value of a digital output.

            :param value: True is on, off is False
            :type  value: bool

            """
>       hal.setDIO(self.port, 1 if value else 0)
E       AttributeError: 'DigitalOutput' object has no attribute 'port'
```

I looked at the object; and it indeed doesn't appear to have a `port` attribute.  Any ideas on what's going on?

**Comment by virtuald** [comment]
Means someone done messed up. I'll upload a fix in a few minutes.

**Comment by virtuald** [comment]
Amusingly, there was a unit test to cover DigitalOutput.get, but not set. :)

**Comment by virtuald** [comment]
Latest release uploaded to pypi and github. Let me know if you run into other issues!

**Comment by codetheweb** [comment]
Now working, thanks!
