### ISSUE TITLE
Add faulthandler

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#266]
For catching segfaults/other stuff

**Comment by Twinters007** [comment]
You said robotpy has no segfaults 😢

**Comment by virtuald** [comment]
Well, that's because I've fixed them by the time you use it. ;)

**Comment by Twinters007** [comment]
Oh but this will catch them instead of it crashing when you test?

**Comment by virtuald** [comment]
Nope. It will just display a python stack trace so you have some chance of figuring out why.

**Comment by Twinters007** [comment]
No SEGFAULT error?

**Comment by virtuald** [comment]
You'll still get that, but you'll get more!
