### ISSUE TITLE
Hal data not entered properly or possibly at all on the command framework

### ISSUE THREAD

**Issue by amboyscout** [robotpy/robotpy-wpilib#275]

**Comment by virtuald** [comment]
You'll need to clarify a bit here. The command framework doesn't cross the HAL boundary, so it wouldn't be in the HAL dictionary.

**Comment by amboyscout** [comment]
Data such as PWM motors and CANTalons are not edited into the hal dictionary when using command code. Hal also does not update the user_program_state when simulating a command based program. 
@virtuald

**Comment by amboyscout** [comment]
Reason for this problem has been discovered: Any hal_data initiated before robotInit is reset to default.

**Comment by virtuald** [comment]
Oh, this is because the command examples use globals? Sigh.

**Comment by virtuald** [comment]
We really should have some mechanism that allows the command based code to work without needing globals. This isn't Java after all.

**Comment by Twinters007** [comment]
#195 should fix all our problems with command based

**Comment by virtuald** [comment]
Closing this as it's technically not our problem -- but we do need to fix the command-based examples to not use globals (@FRC2539 do you have any ideas for this?) . I've opened up a separate issue over in the examples repo.
