### ISSUE TITLE
Prevent installation of simulated hal on roborio

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#303]
This can lead to really difficult to debug situations. Related to https://github.com/robotpy/robotpy-ctre/issues/16

Additionally, we should output a log message or something when the robot code starts, to make it obvious that it's in simulation mode.

**Comment by stmobo** [comment]
I suppose I'll start off by trying to tackle this issue.

**Comment by virtuald** [comment]
@stmobo did you do anything related to this?

**Comment by stmobo** [comment]
Ah, sorry. I meant to start working on it; I've been dealing with school for the past week, though.

I've got free time now, though!
