### ISSUE TITLE
Phase out Python 3.4 support

### ISSUE THREAD

**Issue by twinters007** [robotpy/robotpy-wpilib#355]
Since we all seem to agree that there's no real need to keep supporting it, we should phase it out.

**Comment by virtuald** [comment]
@robotpy/developers (and anyone else) let's vote on this -- get rid of Python 3.4 support now or keep it?

I vote indifferent, preferring to get rid of it if it makes life easier.

**Comment by ariovistus** [comment]
I vote drop it

**Comment by Twinters007** [comment]
I wouldn't even be opposed to only supporting 3.6...

**Comment by auscompgeek** [comment]
I'm indifferent about this.

Let's not be too hasty about dropping 3.5 support though. PyPy3 is still on 3.5 (and even then it's a beta for x86-64 only 😢).

**Comment by virtuald** [comment]
I am opposed to dropping 3.5.

**Comment by Twinters007** [comment]
I'm indifferent to 3.5, but i don't see how we can solve #157 with 3.4 support

**Comment by auscompgeek** [comment]
Backports are a thing.

**Comment by Twinters007** [comment]
I don't know what those are

**Comment by virtuald** [comment]
I think the results are in, sounds like it's out.

**Comment by auscompgeek** [comment]
Given we've managed to sneak in code that only works on Python 3.5+ now (writing docstrings of properties), I think this now means that we no longer support Python 3.4 at all.
