### ISSUE TITLE
PIDController does not have deterministic timing

### ISSUE THREAD

**Issue by PeterJohnson** [robotpy/robotpy-wpilib#38]
As currently written, PIDController doesn't repeat at deterministic intervals because it uses a timed sleep instead of being started periodically.  For example, if the PID get or set functions take variable amounts of time to run, the loop timing changes, which is undesirable for controller time-dependent I and D gain settings.

**Comment by virtuald** [comment]
From my experiments with PreciseDelay, I suspect that this fix was better than nothing, but isn't a complete fix. Something similar to [PreciseDelay](https://github.com/robotpy/robotpy-wpilib-utilities/blob/master/robotpy_ext/misc/precise_delay.py) should be implemented.

**Comment by ThadHouse** [comment]
One thing I noticed is that the C++ code uses the FPGA Notifier to run the PIDController. I know that 254 submitted a patch that added Notifier support to Java. If Notifier support was added here, it could potentially be used for PIDController to give it better timing. 

254s patch does have a bug in it where it gets stuck in an infinite while loop with more then 2 notifiers, but its fixable with 2 lines of code.

I don't know enough python to implement this myself, but maybe over the summer I'll learn enough to try and do it.

**Comment by virtuald** [comment]
@ariovistus ... so in your testing, is this bug moot then?

**Comment by ariovistus** [comment]
for period in the neighborhood of 1 ms, notifier based is definitely better.

**Comment by virtuald** [comment]
Yeah... but if you're using 1ms notifier you're probably going to have other problems.

**Comment by ariovistus** [comment]
like what? (is late, my mind isn't moving quickly)

**Comment by auscompgeek** [comment]
You'd probably have GIL contention problems at that rate.
