### ISSUE TITLE
DriverStation repeatedly printing stacktrace on robot boot-up

### ISSUE THREAD

**Issue by VergilTheHuragok** [robotpy/robotpy-wpilib#415]
Having deployed the code to the bot, the driver station is now repeatedly printing off [this stracktrace](https://github.com/robotpy/robotpy-wpilib/files/1613512/crashreport.txt) which I have copied into a txt. I'm kind of new to all this so please let me know what information is needed to reproduce/resolve this issue. If it is useful, the code I deployed to the robot can be found [here.](https://github.com/VergilTheHuragok/WIP_2017_Python_FRC_Robot_Team_3172/blob/master/robot.py)

**Comment by virtuald** [comment]
That's quite useful, thanks!

**Comment by virtuald** [comment]
Thanks for the bug report! Upgrade RobotPy to 2018.0.1 and the issue should be fixed.
