### ISSUE TITLE
wpi_talonsrx modules' setInverted method not implemented

### ISSUE THREAD

**Issue by amorygalili** [robotpy/robotpy-wpilib#428]
I get this error when I try to call ctre.wpi_talonsrx.WPI_TalonSRX's setInverted method:

self = <ctre.wpi_talonsrx.WPI_TalonSRX object at 0x06626230>, invert = True

    def setInverted(self, invert: bool) -> None:
        assert isinstance(invert, bool)
>       raise NotImplementedError
E       NotImplementedError

..\..\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ctre\_impl\autogen\motcontroller_sim.py:56: NotImplementedError

**Comment by auscompgeek** [comment]
Yes, simulation is not implemented.

**Comment by auscompgeek** [comment]
Also, issues with robotpy-ctre should be reported there, not here.

**Comment by amorygalili** [comment]
I'm confused, is this going to be fixed?

**Comment by auscompgeek** [comment]
It is intended to be fixed soon, yes. Feel free to help out, I guess?

**Comment by amorygalili** [comment]
Sure, if I get to it first although I think @virtuald said he was going to look at it.
