### ISSUE TITLE
:inherited-members: in docs

### ISSUE THREAD

**Issue by ArchdukeTim** [robotpy/robotpy-wpilib#444]
With all the subclassing wpilib has, it can be very useful to see the inherited members of a class. I think we should add this feature of showing all the functions a class has.

**Comment by auscompgeek** [comment]
I dunno about this. A lot of the methods in things like SensorBase aren't really relevant to actually using things like AnalogAccelerometer, for example.

**Comment by virtuald** [comment]
Well. You're probably both right. Maybe we can figure out how to filter out things we don't want to propagate up? All the doc stuff is autogen'ed anyways.

**Comment by auscompgeek** [comment]
Well, luckily all the base classes are listed in the docs anyway, so it's not a major problem if we bikeshed this.

**Comment by virtuald** [comment]
🚴

**Comment by twinters007** [comment]
I was thinking about things like SensorBase that we'd wanna hide...Maybe we cherrypick certain things? I know things like the drive bases are widely used, and it'd be nice to show `setDeadband` in `DifferentialDrive`

**Comment by virtuald** [comment]
I think try it out, build it locally, and once you're happy with something then PR it and we can take a look.

**Comment by twinters007** [comment]
Ok
