### ISSUE TITLE
Make HAL things easier to discover

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#446]
It's really difficult for newcomers to RobotPy to figure out what the hal_data is, how to use it, and what keys they need to use to do various simulation tasks.

This is of course a documentation issue, but perhaps we can do something in the program too to make it easier. Like.. maybe if HAL_DEBUG=1 is set in the environment, then the first time any hal dictionary item is read, the key is printed to stdout?

Another idea could be a module that you execute... maybe `python -m hal.explorer` that would print out the HAL dictionary and allow easy search/discovery? Though, would need some associated metadata too...

**Comment by auscompgeek** [comment]
OBE.
