### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by ariovistus** [robotpy/robotpy-wpilib#462]
is being thrown in the unittests of our command based robot code

example build:
https://travis-ci.org/Retro3223/robot2018/builds/347137201?utm_source=github_status&utm_medium=notification

**Comment by auscompgeek** [comment]
This is very odd… I can't find any writes to LiveWindow.components that aren't protected by the mutex.

**Comment by virtuald** [comment]
Well, you guys are doing something weird, during tests there are ~1500 items in LiveWindow

**Comment by virtuald** [comment]
Looks like everytime you call getJoystick, a new Joystick and JoystickButton are created... and for whatever reason JoystickButton is Sendable. Doesn't explain the error, but you should probably fix that.

**Comment by virtuald** [comment]
If the user does something silly like create a component in the middle of getting values for LiveWindow, then this error occurs. Fixed it so we just make a copy of the dictionary values.

You should probably not create so many JoystickButton objects.
