### ISSUE TITLE
Migrate git-source-track stuff to unified repo layout

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#469]

**Comment by auscompgeek** [comment]
This pretty much only affects pynetworktables and cscore, right?

If nobody else gets around to it, I'll probably tackle this for pynetworktables.

Probably best to start off by making sure everything is up to date to the old repo first, then do the move to the new repo in a new commit.

**Comment by virtuald** [comment]
Seems done.
