### ISSUE TITLE
Update RobotPy for 2019

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-wpilib#474]
Opening this meta-issue early this year for the PyCon AU sprints (next week).

For those of you new to this project, every year we have to update RobotPy's source code to match whatever changes they made to WPILib. It's a bit time consuming and a very manual process.

Last year was a bit of an outlier due to the large changes in WPILib, but in the past we mostly ported things over by the end of October.

We have some tools that help out with this. If you're interested in helping out then check out our porting guide at <http://robotpy.readthedocs.io/en/latest/dev/porting.html>. If the instructions don't make sense, please comment here so we can update them.

Note that the summer hasn't ended in the US yet, and the WPILib team do still have a couple of outstanding projects, so things are still subject to significant change, but I think the bulk of the work has died down now.

To coordinate and avoid duplicating effort, please comment on this issue stating which classes you intend to work on.

**Comment by virtuald** [comment]
One big thing that needs to be done across our repos is update git-source-track lines to match the new repo, as they now have a mega repo which will mess with our tracking stuff...

**Comment by virtuald** [comment]
Sorry... I've been super busy at work this year.

**Comment by auscompgeek** [comment]
Hey, no biggie. We all have lives, and no one person should have to take on all the work of a semi-large project.

I don't think we've actually asked for help on the usual channels yet, so that'd probably be good to do.

**Comment by auscompgeek** [comment]
There are also various tasks listed on https://github.com/orgs/robotpy/projects/3. I've tried to order them based on rough priority.

**Comment by auscompgeek** [comment]
Dibs on Watchdog.

**Comment by auscompgeek** [comment]
Before anyone decides to jump on the MotorSafety changes, it looks like upstream have decided to revert MotorSafety using Watchdog: wpilibsuite/allwpilib#1517

**Comment by auscompgeek** [comment]
Incoming changes to MotorSafety, LiveWindow, IterativeRobotBase, RobotState, and command.PIDSubsystem.

**Comment by auscompgeek** [comment]
Other than Ultrasonic, I think this is pretty much done.
