### ISSUE TITLE
Add mechanism to update hal_in_data

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#530]
Since @amorygalili is working on the websim again this year, we had originally set up a mechanism to ensure that the incoming hal data from the websim didn't accidentally overwrite outputs. Unfortunately, with the dynamic device stuff (namely CAN devices), those devices don't participate. Need to add an API to register a new device, which will then call a callback with the partial information, which the websim can pass on to the UI.

**Comment by auscompgeek** [comment]
Is this still relevant in any way?
