### ISSUE TITLE
Stop using deprecated classes and methods

### ISSUE THREAD

**Issue by twinters007** [robotpy/robotpy-wpilib#538]
No reason to test Robotdrive since we aren't updating it

**Comment by virtuald** [comment]
Yeah, but the code still exists, so it needs to have tests to ensure we don't accidentally break it. This seems like a better fit:  https://docs.pytest.org/en/latest/warnings.html

**Comment by twinters007** [comment]
But we aren't gonna change the code, so can't just skip them in tests? It'll speed things up.

**Comment by virtuald** [comment]
We change things that the code depends on.

**Comment by twinters007** [comment]
Doesn't being deprecated mean that we don't guarantee those things will work with new changes?

**Comment by virtuald** [comment]
No, it means that it will eventually be removed so you shouldn't use it.

One thing we should definitely do is remove deprecated stuff from the examples. But as long as the code is here, it needs to stay tested because someone could use it.
