### ISSUE TITLE
Proper logging in MotorSafety causes recursion error on Python 3.6

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#560]
This is a weird one. In `MotorSafety.check`, the logger.warning causes a weird recursion when the `%` is removed. In case you don't want to run all the tests, I found this reproduces the issue on 3.6.7:

```
wpilib/tests/run_tests.sh -x test_hal_sim.py test_motorsafety.py
```

Should get to the bottom of this. @ArchdukeTim mentioned that this might be caused by improper typing annotations.

**Comment by auscompgeek** [comment]
I think we decided that this is probably due to the typing module recursing on another copy of itself that is registered with abc, since we wipe away all the modules that are loaded on each test.

**Comment by auscompgeek** [comment]
OBE.
