### ISSUE TITLE
Add method to add CameraServer widget to Shuffleboard

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-wpilib#568]
Our CameraServer runs out-of-process, so we need to add a way of adding a Shuffleboard camera widget by name.

**Comment by auscompgeek** [comment]
This would probably be a good thing to have upstream as well actually...

**Comment by virtuald** [comment]
Hm, is https://github.com/wpilibsuite/shuffleboard/issues/582 related?

**Comment by auscompgeek** [comment]
I filed wpilibsuite/allwpilib#1587 last week about this.
