### ISSUE TITLE
curvatureDrive broken on hal.report()

### ISSUE THREAD

**Issue by WinstonHartnett** [robotpy/robotpy-wpilib#585]
**Problem**
Whenever trying to call curvatureDrive() on a DifferentialDrive instance, it reports a resource type that isn't listed in hal/constants.py. Resource type naming conventions were changed in [update differentialdrive for 2019](https://github.com/robotpy/robotpy-wpilib/commit/bcd563f034c15f818429ccdc182213ae9dcc44cf#diff-0072bf9cc22f517a4d4023c4115debb8), but it seems kRobotDrive2_Curvature was not updated in curvatureDrive()'s hal.report() to match the new pattern.

**Test Error**
    
    self = <wpilib.drive.differentialdrive.DifferentialDrive object at 0x000001BD49982748>
    xSpeed = 0.8, zRotation = 0.8, isQuickTurn = False

    def curvatureDrive(
        self, xSpeed: float, zRotation: float, isQuickTurn: bool
    ) -> None:
        """
        Curvature drive method for differential drive platform.

        The zRotation argument controls the curvature of the robot's path rather than its rate
        of heading change. This makes the robot more controllable at high speeds. Also handles
        the robot's quick turn functionality - "quick turn" overrides constant-curvature turning
        for turn-in-place maneuvers

        :param xSpeed: The robot's speed along the X axis `[-1.0..1.0]`. Forward is positive.
        :param zRotation:  The robot's rotation rate around the Z axis `[-1.0..1.0]`. Clockwise is positive.
        :param isQuickTurn: If set, overrides constant-curvature turning for
                          turn-in-place maneuvers.
        """
        if not self.reported:
            hal.report(
                hal.UsageReporting.kResourceType_RobotDrive,
                2,
    >               hal.UsageReporting.kRobotDrive2_Curvature,        <------------------
            )
    E           AttributeError: type object 'UsageReporting' has no attribute 'kRobotDrive2_Curvature'

    C:\Python37\lib\site-packages\wpilib\drive\differentialdrive.py:206: AttributeError

**hal/constants.py**

    class UsageReporting:
        # enum tResourceType
        ...
        kRobotDrive2_DifferentialTank = 8
        kRobotDrive2_DifferentialCurvature = 9                <-------------------
        kRobotDrive2_MecanumCartesian = 10
        ...

[**update differentialdrive for 2019**](https://github.com/robotpy/robotpy-wpilib/commit/bcd563f034c15f818429ccdc182213ae9dcc44cf#diff-0072bf9cc22f517a4d4023c4115debb8)

    138 hal.UsageReporting.kRobotDrive_ArcadeStandard    --->    139 hal.UsageReporting.kRobotDrive2_DifferentialArcade
    
    262 hal.UsageReporting.kRobotDrive_Tank    --->    263 hal.UsageReporting.kRobotDrive2_DifferentialTank
    
    195 hal.UsageReporting.kRobotDrive_Curvature    ---->    196 hal.UsageReporting.kRobotDrive2_Curvature

**Comment by auscompgeek** [comment]
I've pushed up a new release fixing this.
