### ISSUE TITLE
Drop Python 3.5 support?

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-wpilib#606]
Python 3.6 has variable annotations, which would be super-helpful for type hinting data classes.

PyPy3 has 3.6 support now (with a beta label - I hear coverage.py is currently a bit broken), so not too much of a concern there in case anyone (we?) wanted to go down that road.

In terms of distro support:
- Debian 9 (Stretch) is 3.5, but 10 (Buster) will be released in the next week with 3.7.
- The only supported Ubuntu release still on 3.5 is 16.04 (Xenial).
- RHEL7 has Python 3.6, of all distros...
- All supported Fedora releases are on 3.7.
- openSUSE Leap 42.3 has 3.4, which we don't support anyway. Leap 15.0-15.1 is 3.6.

**Comment by virtuald** [comment]
I'm supportive of this.

**Comment by auscompgeek** [comment]
I guess someone should make the PRs to remove 3.5 from CI. I'd like to see the magicbot examples updated to use the variable annotation syntax.

**Comment by M-Shadow** [comment]
Think that should be about it. Any other repos that need updating to CI/updating in general based on this?

**Comment by virtuald** [comment]
pyfrc, pynetworktables, navx, rev... we have a lot of repos. 

FWIW, robotpy-build uses f-strings, so that's definitely going to be 3.6 only.

**Comment by auscompgeek** [comment]
We should also make sure the setup.py files list the 3.8 Trove classifier and not the 3.5 one as well.

**Comment by virtuald** [comment]
Done.
