### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by Nucl3arSn3k** [robotpy/robotpy-wpilib#610]
Good day. Whenever I attempt to run the robot sim I get this error.

`py -3 robot.py sim
Traceback (most recent call last):
  File "robot.py", line 4, in <module>
    from wpilib.shuffleboard import Shuffleboard
ModuleNotFoundError: No module named 'wpilib.shuffleboard'`

However,I've installed all the dependencies that are listed on the readthedocs,and shouldn't be getting this error. Is there any solution for this issue? Thanks.

**Comment by virtuald** [comment]
Closed due to no response.
