### ISSUE TITLE
Unable to import trajectory or controller

### ISSUE THREAD

**Issue by adam-mcdaniel** [robotpy/robotpy-wpilib#637]
![robotpy errors](https://user-images.githubusercontent.com/28228031/74087531-3df27280-4a5b-11ea-85d4-a6a04c045847.png)

**Comment by adam-mcdaniel** [comment]
Our team needs to be able to access the RamseteController object. In the previous RobotPY version, it was in the main package scope, but now Im under the impression that its in the controller module

**Comment by virtuald** [comment]
Oh, I see what happened. Sorry about that, @auscompgeek renamed them. Will push an updated release in a few minutes.

**Comment by virtuald** [comment]
Fixed in 85f1f6f1e999d4055bda6a7198f8cdf5d6a6c557

**Comment by virtuald** [comment]
Once 2020.2.2.7 finishes building (maybe 10 minutes?), this fix should be available for simulation. Just uploaded for roborio.
