### ISSUE TITLE
Add Swerve Drive support

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#667]
We have templates, should be doable now. I think we probably should just suffix with the number of modules supported, and support common configurations.

My understanding is 3, 4, and 6 modules are probably most likely.

As requested on https://www.chiefdelphi.com/t/swerve-drive-kinematics/378774/2

**Comment by KenwoodFox** [comment]
Was this completed?

**Comment by virtuald** [comment]
Yes, that's why the ticket says "closed in 4df5129"

**Comment by KenwoodFox** [comment]
Awesome! Thanks so much! Should have looked more closely, it looked like automation closed the issue but now i see that you did.

**Comment by virtuald** [comment]
There's a bunch of docs at https://robotpy.readthedocs.io/projects/wpimath/en/stable/wpimath.kinematics.html

**Comment by KenwoodFox** [comment]
> There's a bunch of docs at [robotpy.readthedocs.io/projects/wpimath/en/stable/wpimath.kinematics.html](https://robotpy.readthedocs.io/projects/wpimath/en/stable/wpimath.kinematics.html)

This is great, thank you so much!
