### ISSUE TITLE
wpilib.shuffleboard not implemented

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#691]
There's a virtual base class in there somewhere which made this tricky to do correctly, though I don't quite remember why that is.

**Comment by virtuald** [comment]
I have something for this, but it needs testing.

**Comment by auscompgeek** [comment]
We currently have a TODO comment:

https://github.com/robotpy/robotpy-wpilib/blob/69cf7d37c1bff7d278464a091ced1a6154ec0ba0/pyproject.toml#L282

Reopening to track this.

**Comment by auscompgeek** [comment]
@virtuald do you recall how exactly it's broken? I presume it's not related to https://github.com/wpilibsuite/BetaTest/issues/80

**Comment by virtuald** [comment]
I feel it was some NT4 thing, but I imagine that's been fixed by now. We should re-enable and add a simple test to make sure it works.
