### ISSUE TITLE
[BUG]: OSError with robotpy-hal library

### ISSUE THREAD

**Issue by SchoolComp2984** [robotpy/robotpy-wpilib#702]
### Problem description

﻿﻿﻿﻿﻿﻿ OSError: /usr/local/lib/python3.10/site-packages/hal/lib/libwpiHal.so: undefined symbol: _ZN5nFPGA16nFRC_2022_22_2_020g_currentTargetClassE ﻿

Robot code succesfully deployed from Visual Studio Code, Roborio 'no-code' light is red and driver station 'no-code' light is red. When not connected to the computer, the 'no-code' light on the Roborio is not on.

### Operating System

Windows

### Installed Python Packages

```text
pip                      21.2.4
pynetworktables          2021.0.0
pyntcore                 2022.3.1.0
robotpy                  2022.0.39
robotpy-ctre             2022.0.5
robotpy-hal              2022.3.1.0
robotpy-rev              2022.0.1
robotpy-wpilib-utilities 2022.0.1
robotpy-wpimath          2022.3.1.0
robotpy-wpiutil          2022.3.1.0
setuptools               58.1.0
wpilib                   2022.3.1.0
```

### Reproducible example code

```text
Simplest robot code with `import wpilib, rev, ctre` in the robot.py file, deployed from VSCode.
```

**Comment by TheTripleV** [comment]
You have to reimage your roborio to the new image.

https://github.com/wpilibsuite/allwpilib/releases/tag/v2022.3.1
