### ISSUE TITLE
[BUG]: Error 404 Building Robotpy-halsim-gui

### ISSUE THREAD

**Issue by Aldhanekaa** [robotpy/robotpy-wpilib#721]
### Problem description

So I tried to install Robotpy 2022 on my Jetson nano which runs on Ubuntu 18.04, it managed to install other else than robotpy-halsim-gui. I choose robotpy 2022 because, [robotpy 2023 doesn't work on Ubuntu 18.04](https://www.chiefdelphi.com/t/python-networktables-and-cscore-on-jetson-nano/423286/3). [
![photo_2023-02-17 11 48 41](https://user-images.githubusercontent.com/67791514/219552505-9f7d91b7-1cd2-477a-8c50-0451a91de265.jpeg) . 

### Operating System

Linux

**Comment by auscompgeek** [comment]
robotpy-halsim-gui is not, and never was, available for ARM64 platforms.

**Comment by virtuald** [comment]
Yeah, this isn't possible to do for 2022 or 2023 because WPILib doesn't publish halsim-gui for ARM.

**Comment by virtuald** [comment]
Actually, they are publishing ARM artifacts now for halsim-gui, but only for 2023 (which isn't going to help you): https://frcmaven.wpi.edu/ui/native/release/edu/wpi/first/halsim/halsim_gui/2023.3.2/
